name = "TruncatedStacktraces"
uuid = "781d530d-4396-4725-bb49-402e4bee1e77"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com> and contributors"]
version = "1.0.0"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]